services:
  - type: web
    name: ai-voice-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        sync: false
      - key: PORT
        fromService:
          type: web
          name: ai-voice-detection-api
          property: port
